import { Transaction } from "../types/transaction";

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 1000,
    date: "2025-05-14",
    type: "Deposit",
    description: "Security Deposit Venmo",
    amountIn: 500,
    amountOut: 0,
    tenant: "Patrick Gallagher",
    notes: "Deposit Received",
    category: "Deposit",
    monthYear: "2025-05"
  },
  {
    id: 1001,
    date: "2025-06-08",
    type: "Income",
    description: "Rent income venmo",
    amountIn: 4515,
    amountOut: 0,
    tenant: "Patrick Gallagher",
    notes: "Rent Received",
    category: "Rent",
    monthYear: "2025-06",
    managementFeePercentage: 30
  },
  {
    id: 1002,
    date: "2025-07-29",
    type: "Deposit Usage",
    description: "Cleaning from deposit",
    amountIn: 0,
    amountOut: 0,
    tenant: "Patrick Gallagher",
    notes: "Used from security deposit",
    category: "Deposit Usage",
    monthYear: "2025-07",
    depositUsageAmount: 200
  },
  {
    id: 1003,
    date: "2025-07-29",
    type: "Cleaning",
    description: "Cleaning Fee",
    amountIn: 0,
    amountOut: 200,
    tenant: "Patrick Gallagher",
    notes: "Paid to cleaner from deposit",
    category: "Cleaning",
    monthYear: "2025-07"
  },
  {
    id: 1004,
    date: "2025-06-08",
    type: "Management Fee",
    description: "Management Fee",
    amountIn: 0,
    amountOut: 1354.5,
    tenant: "Patrick Gallagher",
    notes: "",
    category: "Management",
    monthYear: "2025-06"
  },
  {
    id: 1005,
    date: "2025-07-01",
    type: "Owner Payout",
    description: "Owner Payout",
    amountIn: 0,
    amountOut: 3160.5,
    tenant: "Patrick Gallagher",
    notes: "",
    category: "Owner Payout",
    monthYear: "2025-07"
  },
  {
    id: 1006,
    date: "2025-07-31",
    type: "Deposit Refund",
    description: "Deposit Returned",
    amountIn: 0,
    amountOut: 300,
    tenant: "Patrick Gallagher",
    notes: "",
    category: "Deposit Refund",
    monthYear: "2025-07"
  },
  {
    id: 1007,
    date: "2025-09-12",
    type: "Income",
    description: "Rent income Zelle",
    amountIn: 3150,
    amountOut: 0,
    tenant: "Jaber",
    notes: "Rent Received",
    category: "Rent",
    monthYear: "2025-09",
    managementFeePercentage: 30
  },
  {
    id: 1008,
    date: "2025-09-13",
    type: "Deposit",
    description: "Security Deposit Zelle",
    amountIn: 500,
    amountOut: 0,
    tenant: "Jaber",
    notes: "Deposit Received",
    category: "Deposit",
    monthYear: "2025-09"
  },
  {
    id: 1009,
    date: "2025-09-12",
    type: "Management Fee",
    description: "Management Fee",
    amountIn: 0,
    amountOut: 945,
    tenant: "Jaber",
    notes: "",
    category: "Management",
    monthYear: "2025-09"
  },
  {
    id: 1010,
    date: "2025-08-11",
    type: "Expense",
    description: "Lockbox",
    amountIn: 0,
    amountOut: 107.74,
    tenant: "NA",
    notes: "Amazon lock box",
    category: "Maintenance",
    monthYear: "2025-08"
  },
  {
    id: 1011,
    date: "2025-10-14",
    type: "Income",
    description: "Rent income cash",
    amountIn: 2000,
    amountOut: 0,
    tenant: "Jaber",
    notes: "Paid direct",
    category: "Rent",
    monthYear: "2025-10",
    managementFeePercentage: 30
  },
  {
    id: 1012,
    date: "2025-10-16",
    type: "Income",
    description: "Rent income cash",
    amountIn: 950,
    amountOut: 0,
    tenant: "Jaber",
    notes: "Zelle to Kyle",
    category: "Rent",
    monthYear: "2025-10",
    managementFeePercentage: 30
  },
  {
    id: 1013,
    date: "2025-10-16",
    type: "Management Fee",
    description: "Management Fee",
    amountIn: 0,
    amountOut: 885,
    tenant: "Jaber",
    notes: "",
    category: "Management",
    monthYear: "2025-10"
  },
  {
    id: 1014,
    date: "2025-11-03",
    type: "Expense",
    description: "Ikea Reimbursement",
    amountIn: 0,
    amountOut: 612,
    tenant: "NA",
    notes: "Paige Records",
    category: "Maintenance",
    monthYear: "2025-11"
  },
  {
    id: 1015,
    date: "2025-11-03",
    type: "Expense",
    description: "Foundation Vents",
    amountIn: 0,
    amountOut: 130,
    tenant: "NA",
    notes: "Paige Records",
    category: "Maintenance",
    monthYear: "2025-11"
  },
  {
    id: 1016,
    date: "2025-11-03",
    type: "Expense",
    description: "Handyman",
    amountIn: 0,
    amountOut: 300,
    tenant: "NA",
    notes: "Paige Records",
    category: "Maintenance",
    monthYear: "2025-11"
  },
  {
    id: 1017,
    date: "2025-11-03",
    type: "Expense",
    description: "Design hrs/install",
    amountIn: 0,
    amountOut: 918,
    tenant: "Na",
    notes: "Paige Records",
    category: "Maintenance",
    monthYear: "2025-11"
  },
  {
    id: 1018,
    date: "2025-11-04",
    type: "Deposit",
    description: "Tia Deposit Pmt",
    amountIn: 500,
    amountOut: 0,
    tenant: "Tia",
    notes: "Received via Zelle",
    category: "Deposit",
    monthYear: "2025-11"
  },
  {
    id: 1019,
    date: "2025-11-04",
    type: "Income",
    description: "Tia Partial Rent Pmt Jan",
    amountIn: 500,
    amountOut: 0,
    tenant: "Tia",
    notes: "Received via Zelle",
    category: "Rent",
    monthYear: "2025-11",
    managementFeePercentage: 30
  },
  {
    id: 1020,
    date: "2025-11-04",
    type: "Management Fee",
    description: "Management Fee",
    amountIn: 0,
    amountOut: 150,
    tenant: "Tia",
    notes: "",
    category: "Management",
    monthYear: "2025-11"
  },
  {
    id: 1021,
    date: "2025-11-04",
    type: "Owner Payout",
    description: "Owner Payout",
    amountIn: 0,
    amountOut: 1437.26,
    tenant: "",
    notes: "Sent ACH",
    category: "Owner Payout",
    monthYear: "2025-11"
  }
];
